version = 0.1
[default.deploy.parameters]
stack_name = "product-app"
resolve_s3 = false
s3_prefix = "product-app"
s3_bucket = "sam-deploy-bucket-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[dev.deploy.parameters]
stack_name = "product-app"
resolve_s3 = false
s3_bucket = "sam-deploy-bucket-aws"
s3_prefix = "product-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
