AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Product API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  ProductAPI:
    Type: AWS::Serverless::Api
   # DeletionPolicy: Retain
    Properties:
      StageName: dev
      Name: ProductAPI
      BinaryMediaTypes:
        - multipart/form-data
        - application/json
  ProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: com.am.product.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 1512
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      PackageType: Zip
      Policies: AWSLambdaBasicExecutionRole
      AutoPublishAlias: SnapStart
      SnapStart:
       ApplyOn: PublishedVersions
      Timeout: 60
      
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            TimeoutInMillis: 20000
            RestApiId: !Ref ProductAPI
            
  ProductDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    #DeletionPolicy: Retain
    Properties:
      TableName: Product
      AttributeDefinitions:
        - AttributeName: productCode
          AttributeType: S
      KeySchema:
        - AttributeName: productCode
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      BillingMode: PROVISIONED
      ContributorInsightsSpecification:
        Enabled: false  #disable because of cost
        
        
  ProductImageS3:
    Type: 'AWS::S3::Bucket'
    #DeletionPolicy: Retain
    Properties:
      BucketName: product-bucket-us
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  ProductCloudFrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        #Aliases:
          #- product.cloudfront.net
        #CNAMEs: 
          #- product.cloudfront.net
        Origins:
          - Id: productApiOrigin
            DomainName: !Sub '${ProductAPI}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          ViewerProtocolPolicy: https-only
          TargetOriginId: productApiOrigin
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
              QueryString: true  #depreciated
              Cookies: 
                Forward: all
          DefaultTTL: 30
          MaxTTL: 30          
        CacheBehaviors:
          - PathPattern: /dev/*  # Path pattern to match requests starting with /dev/
            TargetOriginId: productApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Cookies: 
                Forward: all
            DefaultTTL: 30
            MaxTTL: 30

    

Outputs:
  SpringBootProductApi:
    Description: URL for application
    Value: !Sub 'https://${ProductAPI}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: SpringBootProductApi
  ProductFunction:
    Description: "ProductFunction Lambda Function ARN"
    Value: !GetAtt ProductFunction.Arn
    
  DynamoDBTableName:
    Description: "Product Table Name"
    Value: !Ref ProductDynamoDBTable
    
  DynamoDBTableArn:
    Description: "Product Table Arn"
    Value: !GetAtt ProductDynamoDBTable.Arn
    
  S3BucketName:
    Description: "S3BucketName For image"
    Value: !Ref ProductImageS3
    
  CloudFrontDomainName:
    Description: "Domain Name For CloudFront"
    Value: !GetAtt ProductCloudFrontdistribution.DomainName